### PR TITLE
Add redraw main snippetArea after reload

### PR DESCRIPTION
**Pull request by martinknor**
because i need globalFormStack at footer

### CODE REVIEW

**Comment by f3l1x** [comment]
WDYT @paveljanda?

**Comment by paveljanda** [comment]
I think that would redraw filter inputs, wouldn't it?

**Comment by paveljanda** [comment]
It definitely would. I dont think this is a good idea.

**Comment by f3l1x** [comment]
So I'm closing it now. Thank you @martinknor anyway.

**Pull request closed without merging**
