### PR TITLE
Add the object to string cast to the Row::getId method

### PR DESCRIPTION
**Pull request by jaroslavlibal**
Related to https://github.com/contributte/datagrid/issues/690 and https://github.com/contributte/datagrid/issues/587

### CODE REVIEW

**Comment by paveljanda** [comment]
@f3l1x I would merge this. 👍

**Comment by paveljanda** [comment]
@jaroslavlibal Could you possibly rebase the master? :)

**Comment by f3l1x** [comment]
Uh, could you please rebase it onto 5.x branch? Master is for PHP 7.

**Comment by f3l1x** [comment]
Thanks. ;-)

**Pull request merged**
