### PR TITLE
Fixed width of filter date range inputs

### PR DESCRIPTION
**Pull request by radekdostal**
Before:
datagrid-before

After:
datagrid-after

### CODE REVIEW

**Comment by paveljanda** [comment]
Actualy, demo page works fine (https://examples.contributte.org/packages/datagrid/filters). Can you find out, what is wrong? Thx

**Comment by radekdostal** [comment]
Try Internet Explorer.

**Comment by paveljanda** [comment]
@radekdostal I don't understand what are you talking about :D

**Comment by radekdostal** [comment]
See https://examples.contributte.org/packages/datagrid/filters in Internet Explorer.

**Comment by paveljanda** [comment]
Sadly though, this breaks down styles in chrome, safari, ff etc

**Comment by paveljanda** [comment]
Screenshot 2020-04-21 at 22 18 01
MS Edge works.

Could you possible find a fix for IE that does not break other browsers' behaviour? Thanks a lot!

**Comment by radekdostal** [comment]
Fixed via https://github.com/contributte/datagrid/commit/3cb3db318e2c6391e36b5f9e0e3d5ff46f2ff8a9.

**Pull request closed without merging**
