### PR TITLE
Fix inline edit request method in Naja

### PR DESCRIPTION
**Pull request by Darneus**
changed ajax call argument for inline edit from "method" to "type"

### CODE REVIEW

**Comment by paveljanda** [comment]
@dakorpar Could you please verify that this update works? I know only that you are using Naja. Thanks a lot!

**Comment by dakorpar** [comment]
@paveljanda works in both cases for me, but from code this PR looks correct, not sure why is working correct for me even now, it sends post request with this code and current release.
IMHO this should be merged

**Comment by paveljanda** [comment]
@dakorpar Thanks for the info!
@Darneus Could you please provide some context why this does not work? Some documentation link or something.. Thanks

**Comment by Darneus** [comment]
@paveljanda it does not work because naja implementation dataGridRegisterAjaxCall maps param "type" to "method" or use "GET" by default, but inline editing provided a "method". It's on line 46 in datagrid.js

**Comment by dakorpar** [comment]
@paveljanda this is same as commit you've merged already:
https://github.com/contributte/datagrid/commit/8c99c500c10bae05ea0d6a834b4fac72fae111bd
so you can close this

**Comment by paveljanda** [comment]
Cool, thanks both!

**Pull request closed without merging**
