### PR TITLE
fixed rendering of result aggregationFunction in template

### PR DESCRIPTION
**Pull request by petrparolek**

### CODE REVIEW

**Comment by paveljanda** [comment]
@petrparolek Is it possible to add some tests that will prove correct functionality and prevent future bugs?

**Comment by dakorpar** [comment]
@paveljanda @f3l1x can this be merged?
Sites that use aggregation on datagrid cannot be upgraded to 5.7 because of that...

**Comment by dakorpar** [comment]
@paveljanda @f3l1x is it possible that new version is released without this PR?
There are no tests to write it's just a template and this is feature that exists for a long time and is not working for already 3 versions released? Can someone actually take time and merge this in? please?

**Comment by f3l1x** [comment]
Hope it won't break anything @dakorpar

**Comment by f3l1x** [comment]
Install it via branch alias `v5.8.0` with `minimal-stability:dev` and `prefer-stable: true`.

**Comment by petrparolek** [comment]
hurááá, konečně. OT: prosím o merge ještě !758

**Comment by paveljanda** [comment]
@petrparolek Chill kámo

**Pull request merged**
