### PR TITLE
Fix error "Please select a valid option." on hidden columns, after filter by visible columns

### LINKED ISSUE #979: PHP warning after submit GroupButtonAction
Nette\Forms\Container::getValues() invoked but the form is not valid.

Same warning after filtering with or without pagination https://github.com/contributte/datagrid/issues/961

datagrid 6.9.0, nette/forms 3.1.3

### PR DESCRIPTION
**Pull request by romanmatyus**
https://github.com/contributte/datagrid/issues/979#issuecomment-915809114

### CODE REVIEW

**Comment by f3l1x** [comment]
LGTM

**Comment by f3l1x** [comment]
@paveljanda ping

**Comment by paveljanda** [comment]
Hi, thanks fot the MR. Could you please prepare a sandbox-like repository where I can test both those situations? You can use our datagrid-sandbox for starts: https://github.com/contributte/playground/tree/master/contributte-datagrid

Why am I asking - I am not sure whether it won't break aby back compatibility and also how it will behave with external fitlers.

Thanks a lot!

**Comment by f3l1x** [comment]
Ping @romanmatyus

**Comment by radimvaculik** [comment]
Closing as @romanmatyus is not responding.

**Pull request closed without merging**
