### PR TITLE
Hotfix/action callback onclick type

### PR DESCRIPTION
**Pull request by xsuchy09**
Just onClick hint type - should be `callable[]` so as array ... PHPStan is helping here.

### CODE REVIEW

**Comment by xsuchy09** [comment]
> This branch has no conflicts with the base branch
Which one?

**Comment by paveljanda** [comment]
Screenshot 2020-05-13 at 17 00 35
this one :)

**Comment by xsuchy09** [comment]
Uff
obrazek

**Comment by paveljanda** [comment]
What? :D

**Comment by xsuchy09** [comment]
So just update it in your repo without PR ... just `callable` vs `callable[]` ... or if you want I can try to reset master in my fork to yours ... let me know.

**Pull request closed without merging**
