### PR TITLE
Add method for setting custom Action href, v6.x

### PR DESCRIPTION
**Pull request by Gappa**
Related to #824.

### CODE REVIEW

**Comment by Gappa** [comment]
Seems the tests fail for 7.4snapshot & nightly versions of PHP, other versions are fine.

**Comment by f3l1x** [comment]
Could you rebase it?

**Comment by Gappa** [comment]
> Could you rebase it?

Uff, never have doing this, but after much trial & error, I think it's done :)

**Comment by radimvaculik** [comment]
@Gappa Could you rebase it, please?

**Comment by Gappa** [comment]
> @Gappa Could you rebase it, please?

Done :)

**Comment by radimvaculik** [comment]
@Gappa Could you fix the issues and rebase it against `next` branch, please?

**Comment by Gappa** [comment]
@radimvaculik I somehow mucked up the rebase/squash :( Is there a way out of this mess?

**Comment by radimvaculik** [comment]
@Gappa I changed the base branch to `next` and all good :)

**Pull request merged**
