### PR TITLE
Added option of setting query hints

### PR DESCRIPTION
**Pull request by juniwalk**
I found myself in need of setting query hints in DoctrineDataSource. I implemented this functionality as I thought it would be good to use.

### CODE REVIEW

**Comment by paveljanda** [comment]
@juniwalk Could you pls fix phpstan errors?

@f3l1x Could you please check it? I am not using doctrine myself so it would be better if you review it. Thanks 👍

**Comment by juniwalk** [comment]
@paveljanda already working on it.

**Comment by juniwalk** [comment]
@paveljanda @f3l1x Hello, anything new? :) For review all you need is to check [this method](https://github.com/doctrine/orm/blob/2.13.x/lib/Doctrine/ORM/AbstractQuery.php#L1031).

**Review by f3l1x — APPROVED** [review]

**Comment by f3l1x** [comment]
It's ok. Thanks @juniwalk

**Pull request merged**
