### PR TITLE
Fixed return annotation

### PR DESCRIPTION
**Pull request by radekprokes**

### CODE REVIEW

**Comment by paveljanda** [comment]
@radekprokes This method return only `static` (`return $this`)

**Comment by radekprokes** [comment]
I know, so I fixed it so and removed the bad callable annotation

**Comment by f3l1x** [comment]
I know it's not part of this PR, but could you please drop PHP 7.2 in Travis? There's unrelated misusage in nextras/orm which failing on PHP 7.2.

**Comment by paveljanda** [comment]
@radekprokes Oh I see, I was confused by the diff colors..
@f3l1x Let's make another PR for that.. https://github.com/contributte/datagrid/pull/660

**Pull request merged**
