### PR TITLE
nextras/orm 4.0: native handling in applyFilterText

### PR DESCRIPTION
**Pull request by martenb**
In nextras/orm ^3.1 was filtering with like operators not supported by default.
The implementation of like operators on joined tables and camel cased columns in datagrid leads to errors, which can be fixed only with hacks.

```php
/** @var DbalCollection|Admin[] $collection */
$collection = $this->orm->admins->findAll();

// fix the datagrid filtering bug on joined tables
$builder = $collection->getQueryBuilder();
$builder->leftJoin('admins', '[personal_data]', 'personalData', '[admins.id]=[personalData.admin_id]');

$grid->setDataSource($collection);

$grid->addColumnText('personalDataFirstname', 'Jméno', 'personalData.firstname')
	->setSortable()
	->setFilterText(); // filterText will not work without manual leftJoin


$grid->addColumnText('camelCase', 'Something')
	->setSortable()
	->setFilterText('camel_case'); // filterText will not work without this fix
```

In nextras/orm ^4.0 is like operators supported by default, so we can fix it for that version.

AFAIK it is impossible to fix it in ^3.1.

### CODE REVIEW

**Comment by martenb** [comment]
I have rebased my branch on current master...

**Comment by paveljanda** [comment]
Nice, thanks!
Would it be possible to add some test though? Thanks

**Comment by martenb** [comment]
@paveljanda what tests exactly? standard tests are passing... https://github.com/contributte/datagrid/blob/master/tests/Cases/DataSources/NextrasDataSourceTest.phpt

do you mean something, that dont work with nextras 3.1 and now works?

**Comment by paveljanda** [comment]
@martenb Yes, exactly. I would appreciate to test the new code somehow. Would it be possible to add from your site?

**Comment by martenb** [comment]
I will look at it.

**Comment by martenb** [comment]
@paveljanda can you look at it? i also changed the version of nextras/orm in composer.json, there was the version ~3.2, which not exists! it was changed by fb230a4880794833ce0b2385caada977f0030369

**Comment by martenb** [comment]
Ok I have added nextras/dbal also to dependencies, because of `E_DEPRECATED: Array and string offset access syntax with curly braces is deprecated`. , so now tests with prefer-lowest fail with right error. I am not sure, how to skip the test for nextras/orm 3.1

**Comment by martenb** [comment]
@paveljanda did you have time to look at it?

**Comment by paveljanda** [comment]
Coolio, thanks!

**Comment by martenb** [comment]
@paveljanda Thanks! Can you release a new version?

**Comment by martenb** [comment]
@f3l1x Can you release a new version with this?

**Comment by paveljanda** [comment]
https://github.com/contributte/datagrid/releases/tag/v6.7.0

**Pull request merged**
