### PR TITLE
Fix prefix translate: data_grid_paginator.latte

### PR DESCRIPTION
**Pull request by accgit**

### CODE REVIEW

**Comment by dakorpar** [comment]
it's kinda huge BC break, this should only be for some new major versions and then all translation strings changed

**Comment by paveljanda** [comment]
Until Packagist can migrate packages, we are leaving ublaboo in the package name anyway. Therefore, this BC break is unnecessary. Sorry.

**Comment by accgit** [comment]
I don't understand it either, because I have to have 2 translations with the ublaboo prefix and the others are contributte.

````yaml
'contributte_datagrid.reset_filter': 'Reset'
'contributte_datagrid.items': 'Items'
'contributte_datagrid.from': 'of'
'contributte_datagrid.all': 'All'
'contributte_datagrid.action': 'Action'
'contributte_datagrid.no_item_found': 'Data not found.'
'contributte_datagrid.here': 'Reset'
'contributte_datagrid.no_item_found_reset': 'Data not found, reset the filter.'
'contributte_datagrid.next': 'Next'
'contributte_datagrid.previous': 'Previous'
'ublaboo_datagrid.next': 'Next'
'ublaboo_datagrid.previous': 'Previous'
'contributte_datagrid.show_filter': 'Show filter'
'contributte_datagrid.show_all_columns': 'Show all'
'contributte_datagrid.group_actions': 'Mass action'
'contributte_datagrid.choose': 'Choose an action'
'contributte_datagrid.execute': 'Confirm action'
'contributte_datagrid.per_page_submit': 'Change'
'contributte_datagrid.hide_column': 'Hide column'
'contributte_datagrid.show_default_columns': 'Show default columns'
'contributte_datagrid.filter_submit_button': 'Search'
```

**Comment by radimvaculik** [comment]
Looks like bad rebase ;)

**Pull request closed without merging**
