### PR TITLE
Return value of BackedEnum when reading Doctrine entity property.

### PR DESCRIPTION
**Pull request by juniwalk**

### CODE REVIEW

**Comment by juniwalk** [comment]
Should I add this elsewhere in Row class?

**Comment by radimvaculik** [comment]
@juniwalk Thanks for PR. Could you introduce some tests as well, please?

**Comment by juniwalk** [comment]
@radimvaculik I added needed test, however it is php8.1 feature, Should I mark it somehow to test only for php8.1?

**Comment by juniwalk** [comment]
Well I fixed the test but that codesniffer error I can't find it and the output doesn't tell you where the issue is.

**Comment by radimvaculik** [comment]
Could you point it to `next` branch, please?

**Comment by juniwalk** [comment]
image

It should be pointed into `next`

**Pull request closed without merging**
