### PR TITLE
Replacement of getName with lookupPath #2

### PR DESCRIPTION
**Pull request by peldax**
Follows https://github.com/contributte/datagrid/pull/627

New branch & rebase.

### CODE REVIEW

**Comment by peldax** [comment]
Ping @paveljanda.

This is the new PR with clean branch and rebase.

**Comment by paveljanda** [comment]
Thank you. There is just one problem: When you define the datagrid like so:

```php
$grid = new DataGrid;

#...

return $grid
```
then the parent is not yet defined. In another words, the `DataGrid` component is not yet attached to the presenter so the `$this->lookupPath()` will throw an exception: `Component of type 'Ublaboo\DataGrid\DataGrid' is not attached to ''.`.

**Comment by peldax** [comment]
Hmm, if we move the `lookupPath()` call from constructor to monitor callback, is there any possible issue?

Or we could lazy load the `componentFullName` property in getter function `getFullName()`.

**Comment by paveljanda** [comment]
This is a good idea.
I would definitely move it to the monitor callback + call `::getFullName()` from everywhere instead of using the `::$componentFullName` property directly. :) + I could you maybe add a `Exception` throw to the `::getFullName()` method when the component has `::$componentFullName === null` (the component is not attached to the presenter yet)? Thanks man. :) I appreciate it

**Comment by peldax** [comment]
I noticed that lookupPath was originally inside monitor (otherwise it couldn't work, as you said), but got moved one level up because of bad merge, sorry about that.

I also noticed you are calling monitor function twice in constructor, is it intented?

**Comment by paveljanda** [comment]
Thank you! :)

**Comment by paveljanda** [comment]
https://github.com/contributte/datagrid/releases/tag/v6.0.1

**Pull request merged**
