### PR TITLE
ColumnStatus fixed for null and ''

### PR DESCRIPTION
**Pull request by BigOHenry**
Fix for https://github.com/contributte/datagrid/issues/803

### CODE REVIEW

**Comment by BigOHenry** [comment]
Is this fix fine for you? If not please tell what is wrong. Thank you!

**Comment by BigOHenry** [comment]
Any reaction pls?

**Comment by f3l1x** [comment]
@paveljanda

**Comment by BigOHenry** [comment]
Why is closed and unmerged?

**Pull request closed without merging**
