### PR TITLE
add missing Ublaboo\DataGrid\Column\Column use to TButtonRenderer

### PR DESCRIPTION
**Pull request by dakorpar**
PHPStan is screaming on this one on my projects :)

### CODE REVIEW

**Comment by paveljanda** [comment]
But there is no mention of this class in that file

**Comment by dakorpar** [comment]
@paveljanda it is in phpdoc comment on line 117 and this cause phpstan error afterwards and no autocomplete in IDE

 32     Call to method setFilterText() on an unknown class
         Ublaboo\DataGrid\Traits\Column.

**Comment by paveljanda** [comment]
Oh I see, I am working on version 6 where there is no line number 117 🙈

**Comment by f3l1x** [comment]
Is it still relevant? @paveljanda

**Comment by paveljanda** [comment]
I do not think so

**Pull request closed without merging**
