### PR TITLE
Open visibility for better inheritance usage.

### PR DESCRIPTION
**Pull request by jannovy**
I have to customize DoctrineDataSource class to improve Doctrine performance. This is the most simple way how to embed my own DoctrineDataSource to DataModel and DataGrid.

### CODE REVIEW

**Comment by radimvaculik** [comment]
@jannovy Why don't you use method `setDataSource`? I don't get your proposal changes.

**Comment by jannovy** [comment]
@radimvaculik The goal is to use a custom implementation of the DoctrineDataSource class. So I have to create child class of DataModel to replace \Ublaboo\DataGrid\DataSource\DoctrineDataSource by my own  \App\DataGrid\DataSource\DoctrineDataSource

Or is there some other shortcut ?

**Comment by radimvaculik** [comment]
@jannovy Did you check this PR? https://github.com/contributte/datagrid/pull/1038/files

**Comment by radimvaculik** [comment]
@jannovy Ping.

**Comment by jannovy** [comment]
@radimvaculik Yes, this is solution for me.

**Comment by radimvaculik** [comment]
@jannovy Can we close this issue?

**Comment by jannovy** [comment]
@radimvaculik Yes, thank you.

**Pull request closed without merging**
