### PR TITLE
Latte lint

### PR DESCRIPTION
**Pull request by radimvaculik**
Wait to be https://github.com/contributte/.github/pull/5 merged...

### CODE REVIEW

**Comment by f3l1x** [comment]
Tohle vypada fajn, jen bych si dovolil navrhnout jinaci postup. V testech je to o neco lepsi a muzeme to i sami konfigurovat.

https://github.com/contributte/webapp-skeleton/blob/master/tests/cases/Integration/Latte/CompilerTest.phpt

**Comment by radimvaculik** [comment]
Ja si myslim, ze je lepsi to prave drzet mimo testy. Jakou dodatecnou konfiguraci mas napriklad na mysli?

**Comment by f3l1x** [comment]
Treba registraci maker a pak treba i filtru.

**Comment by radimvaculik** [comment]
Damn it 😞

**Pull request closed without merging**
