### PR TITLE
It is possible to hide columns even with rememberState set to false

### PR DESCRIPTION
**Pull request by RiKap**
It is PR for issue #836 
Just let me know what do you think. :) @paveljanda

### CODE REVIEW

**Comment by RiKap** [comment]
Ping @paveljanda @f3l1x

**Comment by RiKap** [comment]
I will ask fot the last time.
@f3l1x @paveljanda 

If it will not help, I will be forced to create my own fork :/

**Comment by paveljanda** [comment]
Thanks :)

**Comment by RiKap** [comment]
@paveljanda Thx 👏

**Comment by paveljanda** [comment]
@RiKap Please see:

1, https://github.com/contributte/datagrid/issues/934
2, https://github.com/contributte/datagrid/releases/tag/v6.5.1
3, Diff: https://github.com/contributte/datagrid/compare/v6.5.0...v6.5.1

**Pull request merged**
