### PR TITLE
Fix unnecessary setting up template while refreshing state

### PR DESCRIPTION
**Pull request by FVesely**

### CODE REVIEW

**Comment by paveljanda** [comment]
@FVesely What should that do? :)

**Comment by FVesely** [comment]
@paveljanda Sorry, maybe I should open an issue first. Without this PR for example an unnecessary select to database is triggered while refreshing state.

**Comment by paveljanda** [comment]
@FVesely Aaah, I see. Shouldn't be that call just after the `$this->onRender($this);`? I mean after the filter assembly.

**Comment by FVesely** [comment]
@paveljanda I don't think so. All required functions are called in handleRefreshState function.

**Comment by juniwalk** [comment]
@FVesely @paveljanda Anything new? How should it be then?

**Comment by paveljanda** [comment]
@FVesely Shouldn't be the `return` in `::render()` method called before `$this->onRender($this);`?

**Comment by FVesely** [comment]
@paveljanda Yes, it should and it's called before `$this->onRender($this);` because it doesn't render anything.

**Comment by paveljanda** [comment]
I like it. Can you maybe call the property `only_refresh_state`?

**Comment by f3l1x** [comment]
I think we can close it, WDYT @paveljanda?

**Comment by paveljanda** [comment]
Yes

**Pull request closed without merging**
