### PR TITLE
V5.x - merge v5.7.3 and fix array_key_exists in getPerPage method

### PR DESCRIPTION
**Pull request by xsuchy09**
Merge v5.7.3 into 5.x branch and fix array_key_exists - this function has only 2 parameters, not 3.

### CODE REVIEW

**Comment by xsuchy09** [comment]
I just change tag v5.7.3 position to the new commit with this fix (with -f param) ...

**Comment by paveljanda** [comment]
Actually, your MR removes a bit much of the original code. I fixed in in the v5.x branch. But thanks!

**Comment by xsuchy09** [comment]
> Actually, your MR removes a bit much of the original code. I fixed in in the v5.x branch. But thanks!

Yes I merged v5.7.3 before my changes ... it shouldn't be there?

**Comment by xsuchy09** [comment]
There is still an issue - see https://github.com/contributte/datagrid/pull/858

**Pull request closed without merging**
