### PR TITLE
Refactoring & improvements vol.1 [OUTDATED]

### PR DESCRIPTION
**Pull request by f3l1x**
- Require PHP 7.1
- Added editorconfig
- Include codesniffer (from ninjify)
- Added some composer scripts
- Fix DibiFluent -> Dibi\Fluent
- Switch ublaboo/responses -> contributte/application
- Upgrade nette/tester v2.0

- ~~Change badge in README (It looks like is passing, but it's not.. xD)~~

### CODE REVIEW

**Comment by paveljanda** [comment]
@f3l1x Some project still use old dibi with only `DibiFluent` class.
What about discarding current master branch (it's old and I do not know what's event there... / or renaming to something else) and creating new master branch from `v5.x`? Then we can merge this PR into master and release new major version with BC breaks (`DibiFluent` -> `Dibi\Fluent`)

**Comment by f3l1x** [comment]
Agreed. I'll raise PHP and some other stuff (based on slack).

**Comment by paveljanda** [comment]
@f3l1x Each time there is type declaration in function arguement and ALSO php doc block type hint - can we remove that duplicit doc-block?

**Comment by f3l1x** [comment]
Yep, it needs to be done manually. :-)

**Comment by f3l1x** [comment]
I'm update to latest ninjify/qa + codestyle. :-)

**Comment by paveljanda** [comment]
👍

**Comment by f3l1x** [comment]
Because I removed the fork, it needs to be reopened (https://github.com/contributte/datagrid/pull/747).

**Pull request closed without merging**
