### PR TITLE
ColumnStatus allow option value: null

### PR DESCRIPTION
**Pull request by milosjanda**
Sometime default status can be null, so it would be fine implement this.

Screenshot 2020-06-30 at 21 37 34

### CODE REVIEW

**Comment by paveljanda** [comment]
This is actually a BC break. Sorry, I won't merge this pull request into master now.

You can simulate that behaviour using for example a MySQL function `IFNULL` (`IFNULL(test_result, "no-result") as test_result`) in combination with:

```php
$grid->addColumnStatus('statuss', 'Status')->setOptions([
	'excused' => 'Omluven',
	'no-result' => 'Nedostavil se'
]);
```

**Comment by milosjanda** [comment]
Sorry i did't see it, no problem.

**Comment by paveljanda** [comment]
Thanks anyway. I hope that the script helped you a bit. :)

**Comment by milosjanda** [comment]
Unfortunetly no, because i'm using Nextras/Orm and Entity. But i will change default status to any defined value (like 'no-result') in MySql instead of null, which solve it. But thank you very much for very nice and usable Grid.

**Pull request closed without merging**
