### PR TITLE
Add onColumnShow and onColumnHide event methods

### PR DESCRIPTION
**Pull request by jiriermis**
adding methods when showing and hiding a column

### CODE REVIEW

**Comment by radimvaculik** [comment]
@jiriermis Hi, could you change the base branch to `next` please? What about the `handleShowAllColumns` and `handleShowDefaultColumns` support?

**Comment by radimvaculik** [comment]
@jiriermis Could you introduce some tests? Thanks.

**Comment by jiriermis** [comment]
@radimvaculik Added `onShowDefaultColumns` and `onShowAllColumns` methods

**Comment by radimvaculik** [comment]
@jiriermis Thanks. Could you introduce some tests, please?

**Pull request merged**
