### PR TITLE
Append all defined attributes to <tr>

### PR DESCRIPTION
**Pull request by natocTo**
Trying fix "issue" mentioned in this thread https://forum.nette.org/cs/30198-datagrid-vlastni-renderovani-tr

Actually don't know if this is safe method how to handle the issue. :)

### CODE REVIEW

**Comment by f3l1x** [comment]
ping @paveljanda, I like it

**Comment by paveljanda** [comment]
👍

**Comment by f3l1x** [comment]
Could you please @natocTo rebase it?

**Comment by natocTo** [comment]
I tried, but actually I don't know what I am doing.
Maybe it was wrong idea rebase with master.

**Comment by f3l1x** [comment]
Well, you should rebase it to v5.x.

**Comment by f3l1x** [comment]
Thanks

**Pull request merged**
