### PR TITLE
Fix for DibiFluent vs Dibi\Fluent sort

### PR DESCRIPTION
**Pull request by elring**
Fix for #661

### CODE REVIEW

**Comment by f3l1x** [comment]
👍

**Comment by paveljanda** [comment]
@elring Can you send a PR also to the master branch? :) Thanks!

**Comment by elring** [comment]
@paveljanda It looks to me that master branch doesn't work with old Dibi - only with new Dibi\Fluent variant. So no need for backward compatibility. 

And the replace to Dibi\Fluent was already done - even in the sort function - by you :)
`$reflection = new \ReflectionClass(Fluent::class);`

**Comment by paveljanda** [comment]
@elring Good point.

**Comment by f3l1x** [comment]
Merged. Thanks.

**Pull request merged**
