### PR TITLE
Naja2 js

### PR DESCRIPTION
**Pull request by attreid**
Fixed issue with naja2 int treeView when expending tree #1000

### CODE REVIEW

**Comment by radimvaculik** [comment]
@attreid Looks good to me. Could you rebase the branch, please?

**Comment by attreid** [comment]
Ok, within a few days :-)

**Comment by attreid** [comment]
master merged

**Comment by radimvaculik** [comment]
Thanks! @paveljanda @f3l1x Please, check this out.

**Comment by paveljanda** [comment]
@f3l1x Pls let me know whether we want that. We are planning to jump to only newest Naja with the new major release you are working on so I will leave that up 2 you.

**Comment by radimvaculik** [comment]
Let's move to Naja 2 only.

**Comment by MartinKokesCz** [comment]
Hello, guys, are you planning to merge this pull request, please? Thank you :-)

**Comment by paveljanda** [comment]
Actually, we are more likely going to merge this bigger PR: https://github.com/contributte/datagrid/pull/1060

It will also include support for Naja 2.

**Comment by radimvaculik** [comment]
Naja2 is already implemented in `next` branch.

**Pull request closed without merging**
