### PR TITLE
Drop Bower + Assets Docs

### PR DESCRIPTION
**Pull request by f3l1x**

### CODE REVIEW

**Comment by petrparolek** [comment]
why did you remove html samle of using of css and js? I would be nice add npm to html.

**Comment by paveljanda** [comment]
@petrparolek Do you have an html sample with bower?

**Comment by petrparolek** [comment]
I recommend something like
```
<link rel="stylesheet" type="text/css" href="{$basePath}/node_modules/happy-inputs/src/happy.css">

<script type="module">
	import happy from '{$basePath}/node_modules/happy-inputs/src/index.js';

	happy.init();
</script>

<link rel="stylesheet" type="text/css" href="{$basePath}/node_modules/bootstrap-datepicker/dist/css/bootstrap-datepicker3.css">
<link rel="stylesheet" type="text/css" href="{$basePath}/node_modules/ublaboo-datagrid/assets/dist/datagrid.css">

<!-- Use this css for ajax spinners -->
<link rel="stylesheet" type="text/css" href="{$basePath}/node_modules/ublaboo-datagrid/assets/dist/datagrid-spinners.css">

<!-- Include this css when using FilterMultiSelect (silviomoreto.github.io/bootstrap-select) -->
<link rel="stylesheet" type="text/css" href="{$basePath}/node_modules/bootstrap-select/dist/css/bootstrap-select.css">

<script src="{$basePath}/node_modules/bootstrap-datepicker/dist/js/bootstrap-datepicker.js"></script>
<script src="{$basePath}/node_modules/jquery-ui-sortable/jquery-ui.min.js"></script>
<script src="{$basePath}/node_modules/ublaboo-datagrid/assets/dist/datagrid.js"></script>

<!-- It is recommended to include this JS file with just a few bits. It refreshes URL on non ajax request -->
<script src="{$basePath}/node_modules/ublaboo-datagrid/assets/dist/datagrid-instant-url-refresh.js"></script>

<!-- Use this little extension for ajax spinners -->
<script src="{$basePath}/node_modules/ublaboo-datagrid/assets/dist/datagrid-spinners.js"></script>

<!-- Include bootstrap-select.js when using FilterMultiSelect (silviomoreto.github.io/bootstrap-select) -->
<script src="{$basePath}/node_modules/bootstrap-select/dist/js/bootstrap-select.js"></script>
<script src="{$basePath}/node_modules/bootstrap-datepicker/dist/locales/bootstrap-datepicker.cs.min.js" charset="UTF-8"></script>

```

**Comment by petrparolek** [comment]
and in package.json something like:
```
{
  "dependencies": {
    "bootstrap-datepicker": "^1.8.0",
    "bootstrap-select": "^1.13.5",
    "happy-inputs": "^2.0.4",
    "jquery-ui-sortable": "^1.0.0",
    "nette-forms": "^3.0.0",
    "nette.ajax.js": "^2.3.0",
    "popper.js": "^1.14.7",
    "ublaboo-datagrid": "^5.7.0"
  }
}
```

**Comment by f3l1x** [comment]
I'm merging it now, we can create a example in the future.  

Here is some datagrid example https://github.com/planette/playground/tree/master/contributte-datagrid.

**Comment by paveljanda** [comment]
@petrparolek thanks, I will try it and use it if it works 👍

**Pull request merged**
