### PR TITLE
Added selecting rows for group action on more pages

### PR DESCRIPTION
**Pull request by sallyx**
This change allows select rows for group action on
more than one page.

It needs some improvements you can help me with:
    - make it optional
    - (optionaly?) hide selected checboxes from not selected pages (add class hidden?).
    - I don't drink coffee, so I'm not sure if  the code is correct :-)

### CODE REVIEW

**Comment by f3l1x** [comment]
I'm not sure if it's still relevant or wanted. Should be merge it?

**Comment by sallyx** [comment]
Its wanted, but I dont think its ready to merge.
At least checkboxes should be hidden by some css class.
I'd like someone have a look at it and give me some feedback.

**Comment by paveljanda** [comment]
I think this feature should exist as a separate frontned library.

**Comment by f3l1x** [comment]
Closing it due to inactivity. Feel free to open it again or send another PR. Thanks. 🎉

**Pull request closed without merging**
