### PR TITLE
Naja support imporvement

### PR DESCRIPTION
**Pull request by n3t**
This patch is solving 2 issues

1/ Naja ajax search using text field filter
```
$grid->addFilterText('name', 'Name')
```
Using this filter before patch will submit whole page, after patch works as expected.

2/ Naja action confirmation
```
$grid->addAction('delete', '', 'delete!')
	->setConfirmation(
		new StringConfirmation('Really?')
	);
```
Before patch no confirmation is displayed at all, action is directly executed, after patch works as expected.

### CODE REVIEW

**Comment by paveljanda** [comment]
Thank you!

**Comment by camohub** [comment]
Can you make a tag please?

**Comment by paveljanda** [comment]
https://github.com/contributte/datagrid/releases/tag/v6.2.11

**Comment by camohub** [comment]
It is not updated in NPM https://www.npmjs.com/package/ublaboo-datagrid. There is still v6.2.10 I dont use Bower. Anybody shoud use it any more. Please make patch for npm not only for Bower https://docs.npmjs.com/misc/developers#publish-your-package

**Comment by camohub** [comment]
???

**Comment by camohub** [comment]
Are you there? Why did you make a tag only for Bower?

**Comment by darkWolf-PR** [comment]
Hi, I have updated datagrid on actual version(from 6.2.11 to 6.2.17) and I still have problem with not working StringConfirmation on delete action - alert shows off, but no matter what I click, item always gets deleted. Cancel doesn´t  work/get recognized. Using Naja 1.7. Other js stuff in Datagrid like filters etc. works as expected.

**Comment by n3t** [comment]
@darkWolf-PR Did you upgrade also your datagrid.js? Note that upgrading datagrid using composer will not automatically upgrade your js files.

**Comment by darkWolf-PR** [comment]
Assets dir gets updated with composer no? Took new files from it. Size was different, did not actually compared em tho. Version numbers in assets files would be nice. It seems there is some problem with that confirms #900

**Pull request merged**
