### PR TITLE
Nnaja support

### PR DESCRIPTION
**Pull request by filipcro**
Added 3 functions to adapt to both `nette.ajx.js` and `Naja.js`.

### CODE REVIEW

**Comment by paveljanda** [comment]
Thanks a lot!

**Comment by paveljanda** [comment]
@filipcro Would you mind me taking some of your changes from your previous pull-request into future versions of datagrid? (mostly the npm part)

**Comment by filipcro** [comment]
Sure, use it. I'll also suggest adding `files` property so npm won't include PHP files.

**Comment by paveljanda** [comment]
Nice, thanks!

**Comment by paveljanda** [comment]
@filipcro In this form, JavaScript console is throwing "naja is not defined" (https://github.com/contributte/datagrid/pull/837/files#diff-29df16b6d259eb43c865c3d6d2e8c4f7R3)

From JavaScript developer, is it OK to fix it likat that?

```js
if (naja) {
```
->
```js
if (typeof naja !== "undefined") {
```

**Comment by paveljanda** [comment]
(https://github.com/contributte/datagrid/commit/051b8932268db1fa4c661fe05a034be48cf0d366)

**Comment by filipcro** [comment]
That will work.

**Comment by MartinSzollos2016** [comment]
@paveljanda, @filipcro 
Are you sure about correct functionality of this merged pull request ?
Which version of Naja did you used ?
I got a bunch of errors:
TypeError: naja.addEventListener(...).bind is not a function datagrid.js:14 - 36 => maybe you should change "}).bind(this)"  to "}.bind(this))" like in Naja doc example.

Naja version 1.7.0

**Comment by dakorpar** [comment]
@MartinSzollos2016  it's because naja is loaded after datagrid. Try loading naja before.
https://github.com/contributte/datagrid/issues/859

**Comment by dakorpar** [comment]
@paveljanda maybe adding this somewhere to docs?

**Comment by MartinSzollos2016** [comment]
@dakorpar 
Still not working properly, TypeError is not thrown but corresponding datagrid extensions are not loaded either.

**Comment by dakorpar** [comment]
which extension for example?
I'm using naja on one of projects and did not noticed problems?

**Comment by MartinSzollos2016** [comment]
Eg.datagrid.confirm don't show any message or auto submit text input causes redirect instead of ajax call.
Could you please send me your init script ? Maybe i have done something wrong. thx

**Comment by paveljanda** [comment]
@MartinSzollos2016 `.bind` removed in 6.2.6

**Pull request merged**
